AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  Sample SAM Template for {{ cookiecutter.project_name }}

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      {%- if cookiecutter.architectures.value != []%}
      Architectures:
      {%- for arch in cookiecutter.architectures.value %}
        - {{arch}}
      {%- endfor %}
      {%- endif %}
      Timeout: 3
      MemorySize: 128
      FunctionName: !Sub ${Environment}-{{ cookiecutter.project_name }} # TODO replace myFunctionName with actual Function Name
      Environment:
        Variables:
          ConfigBucket: !Sub ${Environment}-{{ cookiecutter.project_name }}
      Policies:
      - AmazonS3FullAccess
      - AmazonAthenaFullAccess
      
